namespace: "softasap"
name: "gitlabrunner_box"
description: wraps sa_gitlab_runner and sa_docker to prepare hosts from gitlabrunner_box group for further provisioning
version: "0.0.1"
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
repository: "https://github.com/oops-to-devops/gitlab_unix_runner"
documentation: "https://github.com/oops-to-devops/gitlab_unix_runner/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
